title: Sai Likith Kumar Reddy Dugganapalli
logo: linkedin pic.png
description: I’m into AI and Data Science because, apparently, that’s what people do when they want to change the world. I know my way around machine learning, deep learning, and data analysis, but don’t worry, I also dabble in Computer Vision, NLP, and Generative AI—because who doesn’t? My toolkit includes Python, TensorFlow, PyTorch, SQL, Pandas, and AWS. Basically, if it involves data or AI, I’ve probably done it… or at least Googled how to do it.
# show_downloads: true
theme: jekyll-theme-cayman
